# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170319_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
    ]
