# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170303_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='heart_rate',
            field=models.IntegerField(default=0, verbose_name='Frequência Cardíaca'),
            preserve_default=False,
        ),
    ]
