# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_monitoring_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
