# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=1000, verbose_name='Assunto'),
        ),
    ]
