# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_monitoring_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='emergency',
            field=models.IntegerField(default=0, verbose_name='Emergência'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
