# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170305_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='steps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passos'),
        ),
    ]
