# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170324_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
