# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170414_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='emergency',
        ),
    ]
