# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_monitoring_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Data/Hora')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Em Andamento'), (2, 'Finalizado'), (3, 'Cancelado')], default=0, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
        ),
    ]
