# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 22:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Foto (URL)'),
        ),
    ]
